spring:
  config:
    activate:
      on-profile: local

  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    root: INFO
    com.gym: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET:am9pbndhdGNocm91dGVkcmVzc3JlY2VpdmVyZWFsY292ZXJtZWJhc2lzZmlsbWFzY2E=}
  expiration-ms: 3600000 # 1 hour

security:
  brute-force:
    max-attempts: 3
    lock-duration-minutes: 5

cors:
  allowed-origins:
