hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/gym-crm-db
hibernate.connection.username=gymUser
hibernate.connection.password=secret

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=validate

hikari.minimumIdle=2
hikari.maximumPoolSize=10
hikari.idleTimeout=30000
hikari.connectionTimeout=10000
hikari.maxLifetime=1800000
