INSERT INTO training_types (training_type_name)
VALUES ('Cardio'),
       ('Strength'),
       ('Yoga'),
       ('CrossFit'),
       ('Pilates'),
       ('Zumba'),
       ('Running'),
       ('Cycling'),
       ('Swimming'),
       ('Boxing'),
       ('Kickboxing'),
       ('HIIT'),
       ('Functional Training'),
       ('Powerlifting'),
       ('Bodybuilding'),
       ('Calisthenics'),
       ('Martial Arts'),
       ('Tennis'),
       ('Basketball'),
       ('Football'),
       ('Volleyball'),
       ('Rowing'),
       ('Stretching'),
       ('Dance Fitness');