package com.gym.service;

import com.gym.dao.InMemoryDao;
import com.gym.model.Training;
import com.gym.model.TrainingType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.util.concurrent.ConcurrentHashMap;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

public class TrainingServiceTest {

    private TrainingService trainingService;
    private InMemoryDao<Training, Long> trainingDao;
    private ConcurrentHashMap<Long, Training> storage;

    @BeforeEach
    public void setup() {
        storage = new ConcurrentHashMap<>();
        trainingDao = new InMemoryDao<>(storage);

        trainingService = new TrainingService();
        trainingService.setTrainingDao(trainingDao);
        trainingService.initSequence();
    }

    @Test
    void createSavesTrainingWithAutoGeneratedId() {
        Training training = buildTraining(1L, 2L, "Morning Yoga", TrainingType.YOGA);

        Training result = trainingService.create(training);

        assertThat(storage).hasSize(1);
        assertThat(storage.get(1L)).isEqualTo(result);
    }

    @Test
    void createIncrementsIdForEachTraining() {
        trainingService.create(buildTraining(1L, 2L, "Morning Yoga", TrainingType.YOGA));
        trainingService.create(buildTraining(1L, 3L, "Evening Cardio", TrainingType.CARDIO));

        assertThat(storage).containsKeys(1L, 2L);
    }

    @Test
    void createThrowsExceptionWhenTrainingIsNull() {
        assertThatThrownBy(() -> trainingService.create(null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void createThrowsExceptionWhenTrainerIdIsNull() {
        Training training = buildTraining(null, 2L, "Morning Yoga", TrainingType.YOGA);

        assertThatThrownBy(() -> trainingService.create(training))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void createThrowsExceptionWhenTrainingNameIsNull() {
        Training training = buildTraining(1L, 2L, null, TrainingType.YOGA);

        assertThatThrownBy(() -> trainingService.create(training))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void initSequenceStartsAtOneWhenStorageIsEmpty() {
        trainingService.create(buildTraining(1L, 2L, "Morning Yoga", TrainingType.YOGA));

        assertThat(storage).containsKey(1L);
    }

    @Test
    void initSequenceContinuesFromMaxExistingId() {
        ConcurrentHashMap<Long, Training> preloaded = new ConcurrentHashMap<>();
        preloaded.put(5L, buildTraining(1L, 2L, "Existing Training", TrainingType.STRENGTH));

        TrainingService freshService = new TrainingService();
        freshService.setTrainingDao(new InMemoryDao<>(preloaded));
        freshService.initSequence();

        freshService.create(buildTraining(1L, 2L, "New Training", TrainingType.CARDIO));

        assertThat(preloaded).containsKey(6L);
    }

    @Test
    void findAllReturnsAllTrainings() {
        storage.put(1L, buildTraining(1L, 2L, "Morning Yoga", TrainingType.YOGA));
        storage.put(2L, buildTraining(3L, 4L, "Evening Cardio", TrainingType.CARDIO));

        assertThat(trainingService.findAll()).hasSize(2);
    }

    @Test
    void findAllReturnsEmptyListWhenNoTrainings() {
        assertThat(trainingService.findAll()).isEmpty();
    }

    @Test
    void findByTrainerIdReturnsMatchingTrainings() {
        storage.put(1L, buildTraining(10L, 2L, "Yoga Session", TrainingType.YOGA));
        storage.put(2L, buildTraining(10L, 3L, "Strength Session", TrainingType.STRENGTH));
        storage.put(3L, buildTraining(99L, 4L, "Other Trainer", TrainingType.CARDIO));

        assertThat(trainingService.findByTrainerId(10L)).hasSize(2);
    }

    @Test
    void findByTrainerIdReturnsEmptyWhenNoMatch() {
        storage.put(1L, buildTraining(10L, 2L, "Yoga Session", TrainingType.YOGA));

        assertThat(trainingService.findByTrainerId(99L)).isEmpty();
    }

    @Test
    void findByTrainerIdThrowsExceptionWhenIdIsNull() {
        assertThatThrownBy(() -> trainingService.findByTrainerId(null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void findByTraineeIdReturnsMatchingTrainings() {
        storage.put(1L, buildTraining(1L, 20L, "Yoga Session", TrainingType.YOGA));
        storage.put(2L, buildTraining(2L, 20L, "Pilates Session", TrainingType.PILATES));
        storage.put(3L, buildTraining(3L, 99L, "Other Trainee", TrainingType.BOXING));

        assertThat(trainingService.findByTraineeId(20L)).hasSize(2);
    }

    @Test
    void findByTraineeIdReturnsEmptyWhenNoMatch() {
        storage.put(1L, buildTraining(1L, 20L, "Yoga Session", TrainingType.YOGA));

        assertThat(trainingService.findByTraineeId(99L)).isEmpty();
    }

    @Test
    void findByTraineeIdThrowsExceptionWhenIdIsNull() {
        assertThatThrownBy(() -> trainingService.findByTraineeId(null))
                .isInstanceOf(NullPointerException.class);
    }

    private Training buildTraining(Long trainerId, Long traineeId, String name, TrainingType type) {
        return Training.builder()
                .trainerId(trainerId)
                .traineeId(traineeId)
                .trainingName(name)
                .trainingType(type)
                .trainingDate(LocalDate.of(2025, 6, 1))
                .trainingDurationMinutes(60)
                .build();
    }
}