CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    is_active  BOOLEAN      NOT NULL
);

CREATE TABLE training_types
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_type_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE trainees
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    date_of_birth DATE,
    address       VARCHAR(255)
);

CREATE TABLE trainers
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    specialization_id BIGINT NOT NULL REFERENCES training_types (id)
);

CREATE TABLE trainings
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id        BIGINT       NOT NULL REFERENCES trainees (id) ON DELETE CASCADE,
    trainer_id        BIGINT       NOT NULL REFERENCES trainers (id),
    training_name     VARCHAR(255) NOT NULL,
    training_type_id  BIGINT       NOT NULL REFERENCES training_types (id),
    training_date     DATE         NOT NULL,
    training_duration INTEGER      NOT NULL CHECK (training_duration > 0)
);

CREATE TABLE trainee_trainer
(
    trainee_id BIGINT NOT NULL REFERENCES trainees (id) ON DELETE CASCADE,
    trainer_id BIGINT NOT NULL REFERENCES trainers (id) ON DELETE CASCADE,
    PRIMARY KEY (trainee_id, trainer_id)
);

CREATE INDEX idx_trainings_trainee_id ON trainings (trainee_id);
CREATE INDEX idx_trainings_trainer_id ON trainings (trainer_id);
CREATE INDEX idx_users_username ON users (username);