spring:
  application:
    name: trainer-workload-service

  profiles:
    default: local

  artemis:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}

  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/trainer_workload}

messaging:
  workload:
    queue: trainer.workload
    dead-letter-queue: trainer.workload.dlq

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

  info:
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true

logging:
  level:
    root: INFO
    com.gym.workload: INFO